require 'uglifier'

task :js do
  files_index = {}
  dirname = File.dirname(File.expand_path(__FILE__))
  Dir.chdir dirname do
    files = Dir.glob(File.join('**', '*.{js,coffee}'))
    files.each do |file|
      files_index[File.basename(file)] = file
    end
  end

  buffer = ""

  main = File.read(File.join(dirname, "js", "main.js"))
  requires = main.scan(/^\/\/=\s+require ([^\s]+)/)
  requires.each do |file|
    raise "File not found: #{file.first}" unless files_index[file.first]
    puts "Found: #{file}"
    buffer << File.read(files_index[file.first])
  end

  buffer << main.split(/^\/\/=\s+require ([^\s]+)/).last
  
  minifier = Uglifier.new
  
  puts "Writing js/compiled.js"
  File.open(File.join("js", "compiled.js"), 'w') do |file|
    file.write "// automatically generated by rake -- do not edit (c) atevans @hired_hq #{Time.now.year}\n"
    file.write minifier.compile(buffer)
  end
  puts "Complete!"
end