task :js do
  files_index = []
  dirname = File.dirname(File.expand_path(__FILE__)
  index = Dir.chdir dirname do
    Dir.glob(File.join('**', '*.{js,coffee}'))
  end

  contents = File.read(File.join(dirname), "js", "main.js"))
  requires = contents.scan(/^\/\/=\s+require ([^\s]+)/)
  requires.each do |file|
    puts file
  end
  # minifier = Uglifier.new
  # File.open(File.join("js", "site.js"), 'w') do |file|
  #   file.write "// automatically generated by rake -- do not edit (c) atevans industries #{Time.now.year}"
  #   file.write minifier.compile(buffer)
  # end
end